---
title: "Computing experiment midlines"
author: "Courtney Goodridge"
date: "16/03/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load packages

```{r}
if(!require(here)) install.packages("here")
library(here)

if(!require(tidyr)) install.packages("tidyr")
library(tidyr)

if(!require(dplyr)) install.packages("dplyr")
library(dplyr)

if(!require(plyr)) install.packages("plyr")
library(plyr)

if(!require(ggplot2)) install.packages("ggplot2")
library(ggplot2)

if(!require(signal)) install.packages("signal")
library(signal)
```

## 1000 radii 

```{r}
myfiles = list.files(path = here::here("Midline_Data"), pattern = "1000_radii", full.names = TRUE)
radii.1000  <- ldply(myfiles, read_csv)

"line visible and creating frame variable"
midline_1000 <- radii.1000 %>%
  dplyr::mutate(trialid = paste(ppid, trialn, sep = "_")) %>%
  dplyr::mutate(LineVis = case_when(BendVisible == TRUE ~ TRUE,
                                    BendVisible == FALSE ~ FALSE)) %>%
  dplyr::filter(LineVis == TRUE) %>%
  dplyr::filter(trialn != -1) %>%
  dplyr::group_by(trialid) %>%
  dplyr::mutate(frame = row_number()) %>%
  dplyr::ungroup() 

"centre x and z coordinates at zero and transform from the global to local"
midline_1000 <- midline_1000 %>%
  dplyr::group_by(trialid) %>%
  dplyr::mutate(World_x_new = World_x - World_x[1]) %>%
  dplyr::mutate(World_z_new = World_z - World_z[1]) %>%
  dplyr::mutate(WorldYaw_rads = WorldYaw / 180 * pi) %>%
  dplyr::mutate(rotatedX = World_x_new * cos(WorldYaw_rads[1]) - World_z_new * sin(WorldYaw_rads[1])) %>%
  dplyr::mutate(rotatedZ = World_x_new * sin(WorldYaw_rads[1]) +  World_z_new * cos(WorldYaw_rads[1])) %>%
  dplyr::ungroup() %>%
  dplyr::group_by(frame) %>%
  dplyr::summarise(x = mean(rotatedX), z = mean(rotatedZ)) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(radii = 1000) 
```

## 1500 radii

```{r}
myfiles = list.files(path = here::here("Midline_Data"), pattern = "1500_radii", full.names = TRUE)
radii.1500  <- ldply(myfiles, read_csv)

"line visible and creating frame variable"
midline_1500 <- radii.1500 %>%
  dplyr::mutate(trialid = paste(ppid, trialn, sep = "_")) %>%
  dplyr::mutate(LineVis = case_when(BendVisible == TRUE ~ TRUE,
                                    BendVisible == FALSE ~ FALSE)) %>%
  dplyr::filter(LineVis == TRUE) %>%
  dplyr::filter(trialn != -1) %>%
  dplyr::group_by(trialid) %>%
  dplyr::mutate(frame = row_number()) %>%
  dplyr::ungroup()

"centre x and z coordinates at zero and transform from the global to local"
midline_1500 <- midline_1500 %>%
  dplyr::group_by(trialid) %>%
  dplyr::mutate(World_x_new = World_x - World_x[1]) %>%
  dplyr::mutate(World_z_new = World_z - World_z[1]) %>%
  dplyr::mutate(WorldYaw_rads = WorldYaw / 180 * pi) %>%
  dplyr::mutate(rotatedX = World_x_new * cos(WorldYaw_rads[1]) - World_z_new * sin(WorldYaw_rads[1])) %>%
  dplyr::mutate(rotatedZ = World_x_new * sin(WorldYaw_rads[1]) +  World_z_new * cos(WorldYaw_rads[1])) %>%
  dplyr::ungroup() %>%
  dplyr::group_by(frame) %>%
  dplyr::summarise(x = mean(rotatedX), z = mean(rotatedZ)) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(radii = 1500)
```

## 2000 radii

```{r}
myfiles = list.files(path = here::here("Midline_Data"), pattern = "2000_radii", full.names = TRUE)
radii.2000  <- ldply(myfiles, read_csv)

"line visible and creating frame variable"
midline_2000 <- radii.2000 %>%
  dplyr::mutate(trialid = paste(ppid, trialn, sep = "_")) %>%
  dplyr::mutate(LineVis = case_when(BendVisible == TRUE ~ TRUE,
                                    BendVisible == FALSE ~ FALSE)) %>%
  dplyr::filter(LineVis == TRUE) %>%
  dplyr::filter(trialn != -1) %>%
  dplyr::group_by(trialid) %>%
  dplyr::mutate(frame = row_number()) %>%
  dplyr::ungroup()

"centre x and z coordinates at zero and transform from the global to local"
midline_2000 <- midline_2000 %>%
  dplyr::group_by(trialid) %>%
  dplyr::mutate(World_x_new = World_x - World_x[1]) %>%
  dplyr::mutate(World_z_new = World_z - World_z[1]) %>%
  dplyr::mutate(WorldYaw_rads = WorldYaw / 180 * pi) %>%
  dplyr::mutate(rotatedX = World_x_new * cos(WorldYaw_rads[1]) - World_z_new * sin(WorldYaw_rads[1])) %>%
  dplyr::mutate(rotatedZ = World_x_new * sin(WorldYaw_rads[1]) +  World_z_new * cos(WorldYaw_rads[1])) %>%
  dplyr::ungroup() %>%
  dplyr::group_by(frame) %>%
  dplyr::summarise(x = mean(rotatedX), z = mean(rotatedZ)) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(radii = 2000)
```
